version: "3.8"

services:
  db:
    image: postgres
    container_name: turing-calendar-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db_new
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"

  turing-calendar-app:
    image: turing-calendar-backend-app:latest
    container_name: turing-calendar
    restart: always
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

volumes:
  postgres:


